name: Linux Release

on:
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
      - name: Build
        run: |
          go mod download
          go build -ldflags "-s -w -extldflags '-static'" -o go-text
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: go-file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}